var especies={"species":[
  {"bio":"People usually think of leopards in the savannas of Africa but in the Russian Far East, a rare subspecies has adapted to life in the temperate forests that make up the northern-most part of the species’ range. Similar to other leopards, the Amur leopard can run at speeds of up to 37 miles per hour. This incredible animal has been reported to leap more than 19 feet horizontally and up to 10 feet vertically. The Amur leopard is solitary. Nimble-footed and strong, it carries and hides unfinished kills so that they are not taken by other predators. It has been reported that some males stay with females after mating, and may even help with rearing the young. Several males sometimes follow and fight over a female. They live for 10-15 years, and in captivity up to 20 years. The Amur leopard is also known as the Far East leopard, the Manchurian leopard or the Korean leopard.",
  "name":"Amur Tiger",
  "status":"Critically Endangered",
  "population":"More than 60 individuals",
  "weight":"75-105 pounds",
  "habitats":"Temperate,Broadleaf,and Mixed Forests",
  "imagepath":"images/amur-leopard.jpg"
},
{"bio":"European hunters are responsible for the early decline of black rhino populations. It was not uncommon for five or six rhinos to be killed in a day for food or simply for amusement. European settlers that arrived in Africa in the early 20th century to colonize and establish farms and plantations continued this senseless slaughter. Most people regarded rhinos as vermin and exterminated them at all costs.",
"name":"Black Rhino",
"status":"Critically Endangered",
"population":"More than 5,000",
"weight":"1,760-3,080 pounds",
"habitats":"Tropical and Subtropical Grasslands,Savannas,Deserts and Xeric Shrublands",
"imagepath":"images/black-rhino.jpg"
},
{"bio":"This subspecies of the western gorilla is very similar in appearance to the more numerous western lowland gorilla, but subtle differences can be found in the skull and tooth dimensions. Cross River gorillas live in a region populated by many humans who have encroached upon the gorilla’s territory—clearing forests for timber and to create fields for agriculture and livestock. Poaching occurs in the forests as well, and the loss of even a few of these gorillas has a detrimental effect on such a small population. Efforts to protect these animals are focused on securing the forests that house them. WWF and partners have worked with the governments of Cameroon and Nigeria to create a protected area for the Cross River gorilla that spans the border of these two nations.",
"name":"Cross River Gorilla",
"status":"Critically Endangered",
"population":"200 to 300 individuals",
"weight":"Up to 440 pounds",
"habitats":"Forest Habitat",
"imagepath":"images/cross-gorilla.jpg"
},
{"bio":"Hawksbills are named for their narrow, pointed beak. They also have a distinctive pattern of overlapping scales on their shells that form a serrated-look on the edges. These colored and patterned shells make them highly-valuable and commonly sold as 'tortoiseshell' in markets. Hawksbills are found mainly throughout the world's tropical oceans, predominantly in coral reefs. They feed mainly on sponges by using their narrow pointed beaks to extract them from crevices on the reef, but also eat sea anemones and jellyfish. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds.",
"name":"Hawksbill Turtle",
"status":"Critically Endangered",
"population":"20,000-30,000 nesting females",
"weight":"90-150 pounds",
"habitats":"Oceans",
"imagepath":"images/hawksbill-turtle.jpg"
},
{"bio":"Javan rhinos are the most threatened of the five rhino species, with 60 individuals surviving in Ujung Kulon National Park in Java, Indonesia. Vietnam’s last Javan rhino was poached in 2010. The Javan rhino is a dusky grey color and has a single horn of up to about 10 inches. Their skin has a number of loose folds giving the appearance of armor plating. This species is very similar in appearance to the closely-related greater-one rhinoceros, but has a much smaller head and less apparent skin folds.",
"name":"Javan Rhino",
"status":"Critically Endangered",
"population":"60",
"weight":"1,984-5,071 pounds",
"habitats":"Tropical forests",
"imagepath":"images/javan-rhino.jpg"
},
{"bio":"Leatherback turtles are named for their shell, which is leather-like rather than hard, like other turtles. They are the largest sea turtle species and also one of the most migratory, crossing both the Atlantic and Pacific Oceans. Pacific leatherbacks migrate from nesting beaches in the Coral Triangle all the way to the California coast to feed on the abundant jellyfish every summer and fall. Although their distribution is wide, numbers of leatherback turtles have seriously declined during the last century as a result of intense egg collection and fisheries bycatch. Globally, leatherback status according to IUCN is listed as Vulnerable, but many subpopulations (such as in the Pacific and Southwest Atlantic) are Critically Endangered.",
"name":"Leatherback Turtle",
"status":"Critically Endangered",
"population":"Less than 2,300",
"weight":"600-1500 pounds",
"habitats":"Oceans",
"imagepath":"images/leatherback-turtle.jpg"
},
{"bio":"As their name implies, mountain gorillas live in forests high in the mountains, at elevations of 8,000 to 13,000 feet. They have thicker fur, and more of it, compared to other great apes. The fur helps them to survive in a habitat where temperatures often drop below freezing. But as humans have moved more and more into the gorillas’ territory, the gorillas have been pushed farther up into the mountains for longer periods, forcing them to endure dangerous and sometimes deadly conditions.",
"name":"Mountain Gorilla",
"status":"Critically Endangered",
"population":"880",
"weight":"Up to 440 pounds",
"habitats":"Forest Habitat,Mountains",
"imagepath":"images/mountain-gorilla.jpg"
},
{"bio":"These solitary, primarily nocturnal animals, are easily recognized by their full armor of scales. A startled pangolin will cover its head with its front legs, exposing its scales to any potential predator. If touched or grabbed it will roll up completely into a ball, while the sharp scales on the tail can be used to lash out. Also called scaly anteaters because of their preferred diet, pangolins are increasingly victims of illegal wildlife crime—mainly in Asia and in growing amounts in Africa—for their meat and scales.",
"name":"Pangolin",
"status":"Critically Endangered",
"population":"Unknown",
"weight":"4.4-7 pounds",
"habitats":"Forests and Grasslands",
"imagepath":"images/pangolin.jpg"
},
{"bio":"The saola was discovered in May 1992 during a joint survey carried out by the Ministry of Forestry of Vietnam and WWF in north-central Vietnam. The team found a skull with unusual long, straight horns in a hunter's home and knew it was something extraordinary. The find proved to be the first large mammal new to science in more than 50 years and one of the most spectacular zoological discoveries of the 20th century. Saola (pronounced: sow-la) are recognized by two parallel horns with sharp ends, which can reach 20 inches in length and are found on both males and females. Meaning “spindle horns” in Vietnamese, they are a cousin of cattle but resemble an antelope. Saola have striking white markings on the face and large maxillary glands on the muzzle, which could be used to mark territory or attract mates. They are found only in the Annamite Mountains of Vietnam and Laos.",
"name":"Saola",
"status":"Critically Endangered",
"population":"Unknown",
"weight":"176-220 pounds",
"habitats":"Evergreen forests with little or no dry season",
"imagepath":"images/saola.jpg"
},
{"bio":"The South China tiger population was estimated to number 4,000 individuals in the early 1950s. In the next few decades, thousands were killed as the subspecies was hunted as a pest. The Chinese government banned hunting in 1979. By 1996 the population was estimated to be just 30-80 individuals. Today the South China tiger is considered by scientists to be “functionally extinct,” as it has not been sighted in the wild for more than 25 years.",
"name":"South China Tiger",
"status":"Critically Endangered",
"population":"Believed to be extinct in the wild",
"weight":"287-386 pounds",
"habitats":"Southeast China-Hainan Moist Forests",
"imagepath":"images/southchina-tiger.jpg"
},
{"bio":"Sumatran elephants feed on a variety of plants and deposit seeds wherever they go, contributing to a healthy forest ecosystem. They also share their lush forest habitat with several other endangered species, such as the Sumatran rhino, tiger, and orangutan, and countless other species that all benefit from an elephant population that thrives in a healthy habitat.",
"name":"Sumatran Elephant",
"status":"Critically Endangered",
"population":"2,400-2,800",
"weight":"Approximately 5 tons",
"habitats":"Broadleaf moist tropical forests",
"imagepath":"images/sumatran-elephant.jpg"
},
{"bio":"The Sumatran orangutan is almost exclusively arboreal, living among the trees of tropical rainforests. Females virtually never travel on the ground and adult males do so rarely. Sumatran orangutans are reported to have closer social ties than their Bornean cousins. This has been attributed to mass fruit on fig trees, where groups of Sumatran orangutans can come together to feed. Adult males are typically solitary while females are accompanied by offspring. Historically, the Sumatran orangutan was distributed over the entire island of Sumatra and further south into Java. The species' range is now restricted to the north of the island with a majority in the provinces of North Sumatra and Aceh.",
"name":"Sumatran Orangutan",
"status":"Critically Endangered",
"population":"Approximately 7,300",
"weight":"66-198 pounds",
"habitats":"Tropical and Subtropical Moist Broadleaf Forests",
"imagepath":"images/sumatran-orangutan.jpg"
},
{"bio":"Sumatran rhinos are the smallest of the living rhinoceroses and the only Asian rhino with two horns. They are covered with long hair and are more closely related to the extinct woolly rhinos than any of the other rhino species alive today. Calves are born with a dense covering that turns reddish brown in young adults and becomes sparse, bristly and almost black in older animals. Sumatran rhinos compete with the Javan rhino for the unenviable title of most threatened rhino species. While surviving in greater numbers than the Javan rhino, Sumatran rhinos are more threatened by poaching. There is no indication that the population is stable and just two captive females have reproduced in the last 15 years.",
"name":"Sumatran Rhino",
"status":"Critically Endangered",
"population":"Less than 100",
"weight":"1,320-2,090",
"habitats":"Dense highland and lowland tropical and subtropical forests",
"imagepath":"images/sumatran-rhino.jpg"
},
{"bio":"Today, the last of Indonesia’s tigers—now fewer than 400—are holding on for survival in the remaining patches of forests on the island of Sumatra. Accelerating deforestation and rampant poaching mean this noble creature could end up like its extinct Javan and Balinese relatives. Sumatran tigers are the smallest surviving tiger subspecies and are distinguished by heavy black stripes on their orange coats. They are protected by law in Indonesia, with tough provisions for jail time and steep fines. But despite increased efforts in tiger conservation—including law enforcement and antipoaching capacity—a substantial market remains in Sumatra and the rest of Asia for tiger parts and products. Sumatran tigers are losing their habitat and prey fast, and poaching shows no sign of decline.",
"name":"Sumatran Tiger",
"status":"Critically Endangered",
"population":"Less than 400",
"weight":"165-308 pounds",
"habitats":"Tropical Broadleaf Evergreen,Forest,Peat Swamps,and Freshwater Swamp Forests",
"imagepath":"images/sumatran-tiger.jpg"
},
{"bio":"Vaquita, the world’s most rare marine mammal, is on the edge of extinction. This little porpoise wasn't discovered until 1958 and a little over half a century later, we are on the brink of losing them forever. Vaquita are often caught and drowned in gillnets used by illegal fishing operations in marine protected areas within Mexico's Gulf of California. More than half of the population has been lost in the last three years. The vaquita has a large dark ring around its eyes and dark patches on its lips that form a thin line from the mouth to the pectoral fins. Its dorsal surface is dark gray, sides pale gray and ventral surface white with long, light gray markings. Newborn vaquita have darker coloration and a wide gray fringe of color that runs from the head to the dorsal flukes, passing through the dorsal and pectoral fins. They are most often found close to shore in the Gulf's shallow waters, although they quickly swim away if a boat approaches.",
"name":"Vaquita",
"status":"Critically Endangered",
"population":"Less than 100",
"weight":"Up to 120 pounds",
"habitats":"Marine(only in the northern Gulf of California)",
"imagepath":"images/vaquita.jpg"
},
{"bio":"The western lowland gorilla is the most numerous and widespread of all gorilla subspecies. Populations can be found in Cameroon, the Central African Republic, the Democratic Republic of Congo and Equatorial Guinea as well as in large areas in Gabon and the Republic of Congo. The exact number of western lowland gorillas is not known because they inhabit some of the most dense and remote rainforests in Africa. Significant populations still exist, including in isolated swamps and the remote swampy forests of the Republic of Congo. Western lowland gorillas can be distinguished from other gorilla subspecies by their slightly smaller size, their brown-grey coats and auburn chests.",
"name":"Western Lowland Gorilla",
"status":"Critically Endangered",
"population":"Unknown",
"weight":"Up to 440 pounds",
"habitats":"Forest Habitat(Congo Basin)",
"imagepath":"images/lowland-gorilla.jpg"
},
{"bio":"The Yangtze River, the longest river in Asia, used to be one of the only two rivers in the world that was home to two different species of dolphin—the Yangtze finless porpoise and the Baiji dolphin. However, in 2006 the Baiji dolphin was declared functionally extinct. This was the first time in history that an entire species of dolphin had been wiped off the planet because of human activity. Its close cousin, the Yangtze finless porpoise, is known for its mischievous smile and has a level of intelligence comparable to that of a gorilla.",
"name":"Yangtze Finless Porpoise",
"status":"Critically Endangered",
"population":"1000-1800",
"weight":"65-100 pounds",
"habitats":"Rivers(Yangtze)",
"imagepath":"images/finless-porpoise.jpg"
},
{"bio":"The wild dog is one of the world’s most endangered mammals. The largest populations remain in southern Africa and the southern part of East Africa (especially Tanzania and northern Mozambique). Wild dogs are social and gather in packs of around ten individuals, but some packs number more than 40. They are opportunistic predators that hunt medium-sized ruminants, such as gazelles. In a sprint, African wild dogs can reach speeds of more than 44 miles per hour.",
"name":"African Wild Dog",
"status":"Endangered",
"population":"3,000-5,500",
"weight":"40-70 pounds",
"habitats":"Deserts,Forests,Grassland",
"imagepath":"images/wild-dog.jpg"
},
{"bio":"Amur tigers were once found throughout the Russian Far East, northern China and the Korean peninsula. By the 1940s, hunting had driven the Amur tiger to the brink of extinction—with no more than 40 individuals remaining in the wild. The subspecies was saved when Russia became the first country in the world to grant the tiger full protection. Amur tigers have the largest home range of any tiger subspecies because they have to search over large areas to find food due to low prey densities. They represent the largest unfragmented tiger population in the world.",
"name":"Amur Tiger",
"status":"Endangered",
"population":"As many as 540",
"weight":"396-660 pounds",
"habitats":"Temperate forest",
"imagepath":"images/amur-tiger.jpg"
},
{"bio":"Asian elephants are extremely sociable, forming groups of six to seven related females that are led by the oldest female, the matriarch. Like African elephants, these groups occasionally join others to form herds, although these associations are relatively transient. More than two thirds of an elephant’s day may be spent feeding on grasses, but large amounts of tree bark, roots, leaves and small stems are also eaten. Cultivated crops such as bananas, rice and sugarcane are favorite foods. Elephants are always close to a source of fresh water because they need to drink at least once a day.",
"name":"Asian Elephant",
"status":"Endangered",
"population":"40,000-50,000",
"weight":"Approximately 11,000 pounds",
"habitats":"Forests",
"imagepath":"images/asian-elephant.jpg"
},
{"bio":"The Bengal tiger is found primarily in India with smaller populations in Bangladesh, Nepal, Bhutan, China and Myanmar. It is the most numerous of all tiger subspecies with more than 2,500 left in the wild. The creation of India’s tiger reserves in the 1970s helped to stabilize numbers, but poaching to meet a growing demand from Asia in recent years has once again put the Bengal tiger at risk. The mangroves of the Sundarbans—shared between Bangladesh and India—are the only mangrove forests where tigers are found. The Sundarbans are increasingly threatened by sea level rise as a result of climate change.",
"name":"Bengal Tiger",
"status":"Endangered",
"population":"More than 2,500",
"weight":"Approximately 550 pounds",
"habitats":"Dry and wet deciduous forests,grassland and temperate forests,mangrove forests",
"imagepath":"images/bengal-tiger.jpg"
},
{"bio":"The black spider monkey—also known as the Guiana or red-faced spider monkey—is found in eastern South America in areas north of the Amazon River. They are one of seven species of spider monkeys found in Latin America and one of the largest primate species in South America.",
"name":"Black Spider Monkey",
"status":"Endangered",
"population":"Unknown",
"weight":"15-19 pounds",
"habitats":"Tropical and subtropical moist broadleaf forests",
"imagepath":"images/spider-monkey.jpg"
},
{"bio":"Once thought to be globally extinct, black-footed ferrets are making a comeback. For the last thirty years, concerted efforts from many state and federal agencies, zoos, Native American tribes, conservation organizations and private landowners have given black-footed ferrets a second chance for survival. Today, recovery efforts have helped restore the black-footed ferret population to nearly 300 animals across North America. Although great strides have been made to recover the black-footed ferret, habitat loss and disease remain key threats to this highly endangered species.",
"name":"Black-footed Ferret",
"status":"Endangered",
"population":"Approximately 300 in the wild",
"weight":"1.5-2.5 pounds",
"habitats":"Grasslands",
"imagepath":"images/footed-ferret.jpg"
},
{"bio":"The blue whale is the largest animal on the planet, weighing as much as 200 tons (approximately 33 elephants). The blue whale has a heart the size of a Volkswagen Beetle. Its stomach can hold one ton of krill and it needs to eat about four tons of krill each day. They are the loudest animals on Earth and are even louder than a jet engine. Their calls reach 188 decibels, while a jet reaches 140 decibels. Their low frequency whistle can be heard for hundreds of miles and is probably used to attract other blue whales.",
"name":"Blue Whale",
"status":"Endangered",
"population":"10,000-25,000",
"weight":"Close to 200 tons",
"habitats":"Oceans",
"imagepath":"images/blue-whale.jpg"
},
{"bio":"Bluefin are the largest tuna and can live up to 40 years. They migrate across oceans and can dive more than 4,000 feet. Bluefin tuna are made for speed: built like torpedoes, have retractable fins and their eyes are set flush to their body. They are tremendous predators from the moment they hatch, seeking out schools of fish like herring, mackerel and even eels. They hunt by sight and have the sharpest vision of any bony fish. There are three species of bluefin: Atlantic (the largest and most endangered), Pacific, and Southern. Most catches of the Atlantic bluefin tuna are taken from the Mediterranean Sea, which is the most important bluefin tuna fishery in the world.",
"name":"Bluefin Tuna",
"status":"Endangered",
"population":"Unknown",
"weight":"1500 pounds",
"habitats":"Oceans",
"imagepath":"images/bluefin-tuna.jpg"
},
{"bio":"Bonobos and chimpanzees look very similar and both share 98.7% of their DNA with humans—making the two species our closest living relatives. Bonobos are usually a bit smaller, leaner and darker than chimpanzees. Their society is also different—bonobo groups tend to be more peaceful and are led by females. They also maintain relationships and settle conflicts through sex. However, bonobo life isn’t entirely violence free; if two groups of bonobos come together, they may engage in serious fighting. Wild bonobos can only be found in forests south of the Congo River in the Democratic Republic of Congo (DRC). Sometimes known as the pygmy chimpanzee, bonobos weren’t recognized as a separate species until 1929. As the last great ape to be scientifically described, much remains unknown about the bonobo—including the extent of its geographic range.",
"name":"Bonobo",
"status":"Endangered",
"population":"10,000-50,000",
"weight":"68-86 pounds",
"habitats":"Forests(Congo Basin)",
"imagepath":"images/bonobo.jpg"
},
{"bio":"Bornean orangutan populations have declined by more than 50% over the past 60 years, and the species' habitat has been reduced by at least 55% over the past 20 years.",
"name":"Bornean Orangutan",
"status":"Endangered",
"population":"45,000-69,000",
"weight":"66-220 pounds",
"habitats":"Lowland rainforests and tropical,swamp and mountain forests",
"imagepath":"images/bornean-orangutan.jpg"
},
{"bio":"Once believed to be remnants of a domesticated herd given to the Sultan of Sulu in the 17th century, pygmy elephants were determined by WWF to be genetically different from other Asian elephants. DNA evidence proved these elephants were isolated about 300,000 years ago from their cousins on mainland Asia and Sumatra. Over time, they became smaller with relatively larger ears, longer tails and straighter tusks. Today, the pygmy elephants of Borneo are the smallest elephants in Asia.",
"name":"Borneo Pygmy Elephant",
"status":"Endangered",
"population":"Approximately 1,500",
"weight":"Unknown",
"habitats":"Forests",
"imagepath":"images/pygmy-elephant.jpg"
},
{"bio":"In their habitat in the forests of central Africa, chimpanzees spend most of their days in the tree tops. When they do come down to earth, chimps usually travel on all fours, though they can walk on their legs like humans for as far as a mile. They use sticks to fish termites out of mounds and bunches of leaves to sop up drinking water. ",
"name":"Chimpanzee",
"status":"Endangered",
"population":"172,700-299,700",
"weight":"Up to 150 pounds",
"habitats":"Forests(moist and dry)",
"imagepath":"images/chimpanzee.jpg"
},
{"bio":"The eastern lowland gorilla—also known as Grauer’s gorilla—is the largest of the four gorilla subspecies. It is distinguished from other gorillas by its stocky body, large hands and short muzzle. Despite its size, eastern lowland gorillas subsist mainly on fruit and other herbaceous materials, just like other gorilla subspecies.",
"name":"Eastern Lowland Gorilla",
"status":"Endangered",
"population":"Unknown",
"weight":"Up to 440 pounds",
"habitats":"Forest(Congo Basin)",
"imagepath":"images/eastern-gorilla.jpg"
},
{"bio":"Next to the blue whale, the fin whale is the second largest mammal in the world. They have a distinct ridge along their back behind the dorsal fin, which gives it the nickname 'razorback.' Fin whales have a very unusual feature: the lower right jaw is bright white and the lower left jaw is black.",
"name":"Fin Whale",
"status":"Endangered",
"population":"50,000-90,000",
"weight":"Almost 80 tons",
"habitats":"Oceans",
"imagepath":"images/fin-whale.jpg"
},
{"bio":"This is the only penguin species found north of the equator and in the Galápagos.",
"name":"Galapagos Penguin",
"status":"Endangered",
"population":"Fewer than 2,000",
"weight":"5.5 pounds",
"habitats":"Oceans",
"imagepath":"images/galapagos-penguin.jpg"
},
{"bio":"The Ganges river dolphin can only live in freshwater and is essentially blind. They hunt by emitting ultrasonic sounds, which bounces off of fish and other prey, enabling them to “see” an image in their mind. They are frequently found alone or in small groups, and generally a mother and calf travel together. Calves are chocolate brown at birth and then have grey-brown smooth, hairless skin as adults. Females are larger than males and give birth once every two to three years to only one calf.",
"name":"Ganges River Dolphin",
"status":"Endangered",
"population":"1,200-1,800",
"weight":"330-374 pounds",
"habitats":"Freshwater Rivers",
"imagepath":"images/gangesriver-dolphin.jpg"
},
{"bio":"The rarest member of the bear family, pandas live mainly in bamboo forests high in the mountains of western China, where they subsist almost entirely on bamboo. They must eat from 26 to 84 pounds of it every day, a formidable task for which they use their enlarged wrist bones that function as opposable thumbs. A newborn panda is about the size of a stick of butter—about 1/900th the size of its mother—but can grow to up to 330 pounds as an adult. These bears are excellent tree climbers despite their bulk.",
"name":"Giant Panda",
"status":"Endangered",
"population":"1,864 in the wild",
"weight":"220-330 pounds",
"habitats":"Temperate broadleaf and mixed forests of southwest China",
"imagepath":"images/giant-panda.jpg"
},
{"bio":"The green turtle is one of the largest sea turtles and the only herbivore among the different species. Green turtles are in fact named for the greenish color of their cartilage and fat, not their shells. In the Eastern Pacific, a group of green turtles that have darker shells are called black turtles by the local community. Green turtles are found mainly in tropical and subtropical waters. Like other sea turtles, they migrate long distances between feeding grounds and the beaches from where they hatched. Classified as endangered, green turtles are threatened by overharvesting of their eggs, hunting of adults, being caught in fishing gear and loss of nesting beach sites.",
"name":"Green Turtle",
"status":"Endangered",
"population":"85,000-90,000",
"weight":"150-400 pounds",
"habitats":"Oceans",
"imagepath":"images/green-turtle.jpg"
},
{"bio":"Hector’s dolphins are the smallest and rarest marine dolphins in the world. They have distinct black facial markings, short stocky bodies and a dorsal fin shaped like a Mickey Mouse ear. There is a subspecies of Hector’s dolphin known as Maui’s dolphin that is critically endangered and estimated to have a population of only 55. They are found only in the shallow coastal waters along western shores of New Zealand’s North Island.",
"name":"Hector's Dolphin",
"status":"Endangered",
"population":"Estimated at 7000",
"weight":"Up to 110 pounds",
"habitats":"Oceans",
"imagepath":"images/hectors-dolphin.jpg"
},
{"bio":"The humphead wrasse is an enormous coral reef fish—growing over six feet long—with a prominent bulge on its forehead. Some of them live to be over 30 years old. They roam through coral reefs in search of hard shelled prey such as mollusks, starfish, or crustaceans. WWF urges local governments in the Coral Triangle to stop the trade and consumption of humphead wrasse—one of the most expensive live reef fishes in the world. Live reef fish trade in Southeast Asia continues to be a significant problem that threatens the region’s food security as well as its reefs, as poachers often resort to legal and destructive fishing methods to catch them.",
"name":"Humphead Wrasse",
"status":"Endangered",
"population":"Unknown",
"weight":"Over 400 pounds",
"habitats":"Oceans",
"imagepath":"images/humhead-wrasse.jpg"
},
{"bio":"Indian elephants may spend up to 19 hours a day feeding and they can produce about 220 pounds of dung per day while wandering over an area that can cover up to 125 square miles. This helps to disperse germinating seeds. They feed mainly on grasses, but large amounts of tree bark, roots, leaves and small stems are also eaten. Cultivated crops such as bananas, rice and sugarcane are favored foods as well. Since they need to drink at least once a day, these elephants are always close to a source of fresh water.",
"name":"Indian Elephant",
"status":"Endangered",
"population":"20,000-25,000",
"weight":"5 tons",
"habitats":"Grasslands",
"imagepath":"images/indian-elephant.jpg"
},
{"bio":"The region contains the largest combined area of tiger habitat in the world—equal to roughly the size of France. However, rapid development, such as road construction, is fragmenting habitats. Due to decades of rampant poaching many of the landscapes of this region have no tigers left in them. There is hope in other remaining Indochinese tiger habitats, which have a relatively low human presence and offer a unique opportunity for tiger conservation. The best hope of the survival of this subspecies is in the Dawna Tennaserim landscape on the Thailand-Myanmar border where perhaps 250 tigers remain. WWF considers the forests of the Lower Mekong a restoration landscape with the possibility of reintroducing tigers as the habitat and prey base are there. Southern Laos and Central Vietnam also have potential for recovery of wild tiger populations.",
"name":"Indochinese Tiger",
"status":"Endangered",
"population":"Around 350",
"weight":"396-550 pounds",
"habitats":"Forests(Great Mekong)",
"imagepath":"images/indochinese-tiger.jpg"
},
{"bio":"Indus river dolphins are one of only four river dolphin species and subspecies in the world that spend all of their lives in freshwater. They are believed to have originated in the ancient Tethys Sea. When the sea dried up approximately 50 million years ago, the dolphins were forced to adapt to its only remaining habitat—rivers. Only about 1,100 exist today in the lower parts of the Indus River in Pakistan. Numbers declined dramatically after the construction of an irrigation system. Most dolphins are confined to a 750 mile stretch of the river and divided into isolated populations by six barrages. They have adapted to life in the muddy river and are functionally blind. They rely on echolocation to navigate, communicate and hunt prey including prawns, catfish and carp.",
"name":"Indus River Dolphin",
"status":"Endangered",
"population":"Approximately 1,100",
"weight":"155-245 pounds",
"habitats":"Freshwaters",
"imagepath":"images/indusriver-dolphin.jpg"
},
{"bio":"Loggerheads are the most common turtle in the Mediterranean, nesting on beaches from Greece and Turkey to Israel and Libya. Many of their nesting beaches are under threat from tourism development. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds.",
"name":"Loggerhead Turtle",
"status":"Endangered",
"population":"Unknown",
"weight":"175-400 pounds",
"habitats":"Oceans",
"imagepath":"images/loggerhead-turtle.jpg"
},
{"bio":"Malayan tigers number around 500 and were classified as the Indochinese tiger until DNA testing in 2004 showed it to be a separate subspecies. Its Latin name—Panthera tigris jacksoni— honors Peter Jackson, the famous tiger conservationist. Malayan tigers are found only on the Malay Peninsula and in the southern tip of Thailand.",
"name":"Malayan Tiger",
"status":"Endangered",
"population":"Around 500",
"weight":"200-264 pounds",
"habitats":"Forests,Grasslands,Wetlands",
"imagepath":"images/malayan-tiger.jpg"
},
{"bio":"The North Atlantic right whale can easily be identified by the white calluses on its head, which are very noticeable against the whale’s dark gray body. It has a broad back without a dorsal fin and a long arching mouth that begins above the eye. A baleen whale, it feeds by swimming through a swarm of plankton with its mouth open and the head slightly above the surface. Right whales are found more often in coastal waters, especially during the breeding season.",
"name":"North Atlantic Right Whale",
"status":"Endangered",
"population":"300-350",
"weight":"Up to 70 tons",
"habitats":"Oceans",
"imagepath":"images/atlanticright-whale.jpg"
},
{"bio":"Sea lions haul out in large colonies on rocks and sandy shores on the Islands. They move into the water to feed and cool off as needed.",
"name":"Sea Lions",
"status":"Endangered",
"population":"Less than 100,000",
"weight":"Around 400 pounds",
"habitats":"Oceans",
"imagepath":"images/sea-lions.jpg"
},
{"bio":"The sei whale is one of the fastest whales, reaching speeds of up to 30 miles per hour. Sei whales inhabit all oceans and adjoining seas except in tropical and polar regions. Like other great whales, they prefer to spend the summer feeding in cooler waters before migrating to warmer waters to breed and give birth to their calves.",
"name":"Sei Whale",
"status":"Endangered",
"population":"Approximately 80,000",
"weight":"About 20 tons",
"habitats":"Oceans",
"imagepath":"images/sei-whale.jpg"
},
{"bio":"The snow leopard’s powerful build allows it to scale great steep slopes with ease. Its hind legs give the snow leopard the ability to leap six times the length of its body. A long tail provides balance and agility and also wraps around the resting snow leopard as protection from the cold. For millennia, this magnificent cat was the king of the mountains. The mountains were rich with their prey such as blue sheep, Argali wild sheep, ibex, marmots, pikas and hares. Snow leopards are found in 12 countries—including China, Bhutan, Nepal, India, Pakistan, Afghanistan, Russia, and Mongolia—but their population is dropping.",
"name":"Snow Leopard",
"status":"Endangered",
"population":"4,080-6,590",
"weight":"77-121 pounds",
"habitats":"Mountains(Eastern Himalayas,Yangtze)",
"imagepath":"images/snow-leopard.jpg"
},
{"bio":"The Sri Lankan subspecies is the largest and also the darkest of the Asian elephants, with patches of depigmentation—areas with no skin color—on its ears, face, trunk and belly. Once found throughout the tear-shaped island at the bottom of India’s southern tip, these elephants are now being pushed into smaller areas as development activities clear forests and disrupt their ancient migratory routes. The herd size in Sri Lanka ranges from 12-20 individuals or more. It is led by the oldest female, or matriarch. In Sri Lanka, herds have been reported to contain nursing units, consisting of lactating females and their young, and juvenile care units, containing females with juveniles. The Sri Lankan elephant population has fallen almost 65% since the turn of the 19th century. Today, the Sri Lanka elephant is protected under the Sri Lankan law and killing one carries the death penalty.",
"name":"Sri Lankan Elephant",
"status":"Endangered",
"population":"2,500-4,000",
"weight":"4,400-12,000",
"habitats":"Tropical and Subtropical Moist Broadleaf Forests",
"imagepath":"images/srilankan-elephant.jpg"
},
{"bio":"The largest of all the Asian big cats, tigers rely primarily on sight and sound rather than smell. They typically hunt alone and stalk prey. A tiger can consume up to 88 pounds of meat at one time. On average, tigers give birth to two or three cubs every two years. If all the cubs in one litter die, a second litter may be produced within five months. Across their range, tigers face unrelenting pressures from poaching, retaliatory killings and habitat loss. They are forced to compete for space with dense and often growing human populations.",
"name":"Tiger",
"status":"Endangered",
"population":"As few as 3,200",
"weight":"220-660 pounds",
"habitats":"Forests,Grasslands,Mangrove Swamps,Savannas",
"imagepath":"images/tiger.jpg"
},
{"bio":"Whales roam throughout all of the world’s oceans, communicating with complex and mysterious sounds. Their sheer size amazes us: the blue whale can reach lengths of more than 100 feet and weigh up to 200 tons—as much as 33 elephants.  Despite living in the water, whales breathe air. And like humans, they are warm-blooded mammals who nurse their young. A thick layer of fat called blubber insulates them from cold ocean waters.",
"name":"Whale",
"status":"Endangered",
"population":"300-90,000(depending on species)",
"weight":"20-200 tons",
"habitats":"Oceans",
"imagepath":"images/whale.jpg"
}

]};
